var mongoose = require('mongoose'),
    debug    = require('debug')('app:models');

// highlighted substring of the article text
var highlightSchema = new mongoose.Schema({
  startChar: Number,
  endChar: Number,
  createdAt: Date,
  text: String,
  addedBy: {type: mongoose.Schema.Types.ObjectId, ref: "User"}


});

var articleSchema = new mongoose.Schema({
  title: String,
  author: String,
  description: String,
  publisher: String,
  url: String,
  text: String,
  images: [String],
  thumbnailImg: String,
  publishedOn: Date,
  subjects: [String], // subjects are generated by the article scraper and are not editable by the user
  tags: [String], // tags are generated/editable by the user
  highlights: [highlightSchema],
  addedBy: [{type: mongoose.Schema.Types.ObjectId, ref: "User"}]
});

articleSchema.methods.addTag = function(newTag) {
  newTag = newTag.toLowerCase();
  if (this.tags.indexOf(newTag) === -1) {
    this.tags.push(newTag);
    return newTag;
  } else {
    return null;
  }
};

// How you add tags by default.
// var article = new Article(...);
// article.tags.push('newTag');
// article.save();

// How you do it now.
// var article = new Article(...);
// article.addTag('newTag');
// article.save();
// if (!article.addTag('newTag')) {
//   res.send('Tag already added!');
// }



var Article = mongoose.model('Article', articleSchema);

module.exports = Article;
